export const categories = [
  { id: "1", name: "Products" },
  { id: "2", name: "Main Courses" },
  { id: "3", name: "Drinks" },
  { id: "4", name: "Desserts" },
  { id: "5", name: "Burgers" },
  { id: "6", name: "Appetizers" },
  { id: "7", name: "Sandwiches" },
  { id: "8", name: "Salads" },
  { id: "9", name: "Soups" },
  { id: "10", name: "Specials" },
];

export const products = {
  Products: [
    { id: "1", name: "Pizza", price: 12.99 },
    { id: "2", name: "Pasta", price: 10.99 },
    { id: "3", name: "Salad", price: 8.99 },
    { id: "4", name: "Sandwich", price: 7.99 },
    { id: "5", name: "Burger", price: 9.99 },
    { id: "6", name: "Fries", price: 3.99 },
    { id: "7", name: "Soda", price: 1.99 },
    { id: "8", name: "Juice", price: 2.99 },
    { id: "9", name: "Coffee", price: 2.49 },
    { id: "10", name: "Tea", price: 2.49 },
  ],
  "Main Courses": [
    { id: "11", name: "Steak", price: 20.99 },
    { id: "12", name: "Chicken Alfredo", price: 15.99 },
    { id: "13", name: "Grilled Salmon", price: 18.99 },
    { id: "14", name: "Ribs", price: 22.99 },
    { id: "15", name: "Lamb Chops", price: 24.99 },
    { id: "16", name: "Pork Chops", price: 17.99 },
    { id: "17", name: "Vegetable Stir Fry", price: 14.99 },
    { id: "18", name: "Beef Stroganoff", price: 19.99 },
    { id: "19", name: "Chicken Parmesan", price: 16.99 },
    { id: "20", name: "Seafood Platter", price: 25.99 },
  ],
  Drinks: [
    { id: "21", name: "Coke", price: 1.99 },
    { id: "22", name: "Lemonade", price: 2.99 },
    { id: "23", name: "Iced Tea", price: 2.49 },
    { id: "24", name: "Beer", price: 3.99 },
    { id: "25", name: "Wine", price: 4.99 },
    { id: "26", name: "Whiskey", price: 5.99 },
    { id: "27", name: "Vodka", price: 5.99 },
    { id: "28", name: "Rum", price: 4.99 },
    { id: "29", name: "Gin", price: 5.49 },
    { id: "30", name: "Martini", price: 6.99 },
  ],
  Desserts: [
    { id: "31", name: "Ice Cream", price: 3.99 },
    { id: "32", name: "Cheesecake", price: 4.99 },
    { id: "33", name: "Brownie", price: 3.49 },
    { id: "34", name: "Apple Pie", price: 4.49 },
    { id: "35", name: "Chocolate Cake", price: 5.99 },
    { id: "36", name: "Cupcake", price: 2.99 },
    { id: "37", name: "Pudding", price: 3.49 },
    { id: "38", name: "Tiramisu", price: 4.99 },
    { id: "39", name: "Creme Brulee", price: 5.99 },
    { id: "40", name: "Gelato", price: 4.99 },
  ],
  Burgers: [
    { id: "41", name: "Cheeseburger", price: 9.99 },
    { id: "42", name: "Veggie Burger", price: 8.99 },
    { id: "43", name: "Bacon Burger", price: 11.99 },
    { id: "44", name: "Mushroom Burger", price: 10.99 },
    { id: "45", name: "Double Cheeseburger", price: 12.99 },
    { id: "46", name: "BBQ Burger", price: 11.49 },
    { id: "47", name: "Turkey Burger", price: 9.99 },
    { id: "48", name: "Fish Burger", price: 10.49 },
    { id: "49", name: "Buffalo Burger", price: 13.99 },
    { id: "50", name: "Slider Trio", price: 12.99 },
  ],
  Appetizers: [
    { id: "51", name: "Mozzarella Sticks", price: 6.99 },
    { id: "52", name: "Chicken Wings", price: 8.99 },
    { id: "53", name: "Spring Rolls", price: 5.99 },
    { id: "54", name: "Garlic Bread", price: 4.99 },
    { id: "55", name: "Nachos", price: 7.99 },
    { id: "56", name: "Onion Rings", price: 5.99 },
    { id: "57", name: "Stuffed Mushrooms", price: 6.99 },
    { id: "58", name: "Bruschetta", price: 5.99 },
    { id: "59", name: "Quesadilla", price: 7.49 },
    { id: "60", name: "Spinach Artichoke Dip", price: 6.99 },
  ],
  Sandwiches: [
    { id: "61", name: "Club Sandwich", price: 8.99 },
    { id: "62", name: "BLT", price: 7.99 },
    { id: "63", name: "Grilled Cheese", price: 6.99 },
    { id: "64", name: "Turkey Sandwich", price: 8.49 },
    { id: "65", name: "Ham Sandwich", price: 7.99 },
    { id: "66", name: "Chicken Sandwich", price: 9.49 },
    { id: "67", name: "Philly Cheese Steak", price: 10.99 },
    { id: "68", name: "Tuna Sandwich", price: 8.49 },
    { id: "69", name: "Pastrami Sandwich", price: 9.99 },
    { id: "70", name: "Egg Salad Sandwich", price: 6.99 },
  ],
  Salads: [
    { id: "71", name: "Caesar Salad", price: 7.99 },
    { id: "72", name: "Garden Salad", price: 6.99 },
    { id: "73", name: "Greek Salad", price: 8.99 },
    { id: "74", name: "Cobb Salad", price: 9.99 },
    { id: "75", name: "Chef Salad", price: 10.99 },
    { id: "76", name: "Tuna Salad", price: 8.49 },
    { id: "77", name: "Chicken Salad", price: 9.49 },
    { id: "78", name: "Antipasto Salad", price: 11.99 },
    { id: "79", name: "Fruit Salad", price: 6.99 },
    { id: "80", name: "Pasta Salad", price: 7.49 },
  ],
  Soups: [
    { id: "81", name: "Chicken Noodle Soup", price: 5.99 },
    { id: "82", name: "Tomato Soup", price: 4.99 },
    { id: "83", name: "Clam Chowder", price: 6.99 },
    { id: "84", name: "Minestrone", price: 5.99 },
    { id: "85", name: "French Onion Soup", price: 6.49 },
    { id: "86", name: "Vegetable Soup", price: 4.99 },
    { id: "87", name: "Beef Barley Soup", price: 6.49 },
    { id: "88", name: "Lentil Soup", price: 5.49 },
    { id: "89", name: "Potato Soup", price: 5.99 },
    { id: "90", name: "Broccoli Cheddar Soup", price: 6.49 },
  ],
  Specials: [
    { id: "91", name: "Surf and Turf", price: 29.99 },
    { id: "92", name: "Lobster Roll", price: 24.99 },
    { id: "93", name: "Filet Mignon", price: 32.99 },
    { id: "94", name: "Duck Breast", price: 27.99 },
    { id: "95", name: "Osso Buco", price: 25.99 },
    { id: "96", name: "Paella", price: 23.99 },
    { id: "97", name: "Bouillabaisse", price: 26.99 },
    { id: "98", name: "Beef Wellington", price: 34.99 },
    { id: "99", name: "Rack of Lamb", price: 28.99 },
    { id: "100", name: "Coq au Vin", price: 21.99 },
  ],
};
